# Description
# Baseline configuration where we use the original CLIP anchor loss
# with temperature as a learnable parameter.

# Identifiers
project_name: "Sparsify_experiments"
run_name: "experiment_6-SPARSIFICATION(1E)+ANCHOR+LALIGN+LUNIF(CENTROIDS)"

# Never change parameters
seed: 42
learning_rate: 1e-4
batch_size: 256
model: "RN50"
num_train_samples: -1
num_test_samples: 512
epochs: 100

# Experiment specific parameters
loss_type: "only_lunif_n_then_anchor+lalign+lunif(centroids)"
only_lunif_epochs: 1
anchor_temperature: 0.1
anchor_temperature_learnable: False

# Evaluation and checkpointing
save_checkpoint_every_n_epochs: 20
resume_checkpoint: False

# fp16
fp16: True
